"""Add User table

Revision ID: 23292277a1ca
Revises: 4f5482383b63
Create Date: 2024-12-06 16:00:54.419922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '23292277a1ca'
down_revision: Union[str, None] = '4f5482383b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgeBasesList', sa.Column('knowledgeBaseId', sa.String(length=18), nullable=True))
    op.drop_column('knowledgeBasesList', 'knowledgeBaseNameId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgeBasesList', sa.Column('knowledgeBaseNameId', mysql.VARCHAR(length=18), nullable=True))
    op.drop_column('knowledgeBasesList', 'knowledgeBaseId')
    # ### end Alembic commands ###
