"""删掉userid,只使用username

Revision ID: 2ea165d11c5c
Revises: 23292277a1ca
Create Date: 2024-12-06 17:06:58.548812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ea165d11c5c'
down_revision: Union[str, None] = '23292277a1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('chat_messages', 'userId')
    op.add_column('conversationsList', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('conversationsList', 'userId')
    op.drop_index('ix_userInfo_userId', table_name='userInfo')
    op.drop_column('userInfo', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userInfo', sa.Column('userId', mysql.VARCHAR(length=18), nullable=True))
    op.create_index('ix_userInfo_userId', 'userInfo', ['userId'], unique=True)
    op.add_column('conversationsList', sa.Column('userId', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('conversationsList', 'username')
    op.add_column('chat_messages', sa.Column('userId', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('chat_messages', 'username')
    # ### end Alembic commands ###
