"""增加数据库配置信息表

Revision ID: 5ea9047c43e3
Revises: 
Create Date: 2024-12-03 16:30:13.409731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea9047c43e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgeConfig',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledgeBaseId', sa.String(length=255), nullable=True),
    sa.Column('rag_model', sa.Integer(), nullable=True),
    sa.Column('is_rerank', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieverDocs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('knowledge_doc_name', sa.String(length=255), nullable=True),
    sa.Column('knowledgeBaseId', sa.String(length=255), nullable=True),
    sa.Column('messageId', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retrieverDocs')
    op.drop_table('knowledgeConfig')
    # ### end Alembic commands ###
